### ISSUE TITLE
add only only plugin dependency cause mysql dependency absent

### ISSUE THREAD

**Issue by Victor-Cooper** [kimichen13/mybatis-generator-plugin#12]
when I add the following configuration to my gradle
    dependencies {
        mybatisGenerator 'org.mybatis.generator:mybatis-generator-maven-plugin:1.4.0'
    }
It fails with "Exception getting JDBC Driver"
If I add the jdbc driver like this it works:
    dependencies {
        mybatisGenerator 'org.mybatis.generator:mybatis-generator-maven-plugin:1.4.0'
        mybatisGenerator 'mysql:mysql-connector-java:5.1.47'
    }
Looks like once I overide one dependency I need to overide all.
Is my understanding of how it works correct? Thanks!

**Comment by kimichen13** [comment]
Yes, once you override one dependency, you need to override all.
Because it cannot be decided automatic which database and which version will be used.
So I just add default `mybatis-generator` dependency and two database dependencies (mysql and postgresql).
