### ISSUE TITLE
MybatisGeneratorTask init error

### ISSUE THREAD

**Issue by lxmin0702** [kimichen13/mybatis-generator-plugin#13]
I have a problem with mbg，cause a "Type 'MybatisGeneratorTask' property 'configFile' is missing an input or output annotation." stacktrace in springboot+gradle+mysql environment. please help me.

**Comment by kimichen13** [comment]
You can see the `MybatisGeneratorPluginFunctionTest` I wrote, you should specify `configFile` in your `build.gradle` file.

Then it will be work.

**Comment by lxmin0702** [comment]
> You can see the [Add configuration](https://github.com/kimichen13/mybatis-generator-plugin#add-configuration) part in `README`.
> 
> Then it will be work.

Thx for reply.Actually I truly added mybatisGenerator configuration according to the README-doc.I'm very confused...I just upload my project to github,Could you check it for me ?[https://github.com/lxmin0702/springboot_gradle/blob/2803fc57a834da0c5dabc8ee493419b379e9e0cb/controller/build.gradle#L49](url)

**Comment by kimichen13** [comment]
> > You can see the [Add configuration](https://github.com/kimichen13/mybatis-generator-plugin#add-configuration) part in `README`.
> > Then it will be work.
> 
> Thx for reply.Actually I truly added mybatisGenerator configuration according to the README-doc.I'm very confused...I just upload my project to github,Could you check it for me ?[https://github.com/lxmin0702/springboot_gradle/blob/2803fc57a834da0c5dabc8ee493419b379e9e0cb/controller/build.gradle#L49](url)

I am not sure about your configuration, it seems ok. But your `configFile` is absolute, and this file usually located in the resources' directory under project. Besides, there are also some configurations in this file should be relative path, for example, the generated files' path. 

According to the error message `missing an input or output annotation`, it means the file is not right for generation. You can check the official website of [mybatis generator](http://mybatis.org/generator/configreference/xmlconfig.html).

**Comment by sciencesakura** [comment]
This problem occurs when using Gradle 7.

https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation

I've sent the PR #11 to fix it.

**Comment by kimichen13** [comment]
> This problem occurs when using Gradle 7.
> 
> https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation
> 
> I've sent the PR #14 to fix it.

I have upgraded to Gradle 7.0. The problem occurs. 
So can you change the PR to develop branch. I will release a new version of the plugin. Thank you.

**Comment by sciencesakura** [comment]
I did it
