### ISSUE TITLE
Cannot use the property generated.source.dir inside mybatis generator config file

### ISSUE THREAD

**Issue by GianniGT** [kimichen13/mybatis-generator-plugin#15]
even if the property 'generated.source.dir' is set in MybatisGeneratorTask.groovy, it cannot be really used in the mybatis generator config file.

The reason is that the property is not set.
You should do something like:

            ant.mbgenerator(overwrite: getOverwrite(), configfile: getConfigFile(), verbose: getVerbose()) {
                propertyset {
                    propertyref(name: 'generated.source.dir')
                }
            }

**Comment by kimichen13** [comment]
Already fix it in #17
