### ISSUE TITLE
This plugin is not using lazy property

### ISSUE THREAD

**Issue by rajpra8** [kimichen13/mybatis-generator-plugin#18]
In our project, we have encrypted database password as property. Only certain developer has access to encryption key. But since it is not lazy property, when automated process is trying to build our project, it fails as it tries to load mybatisProperties

https://github.com/kimichen13/mybatis-generator-plugin/blob/9905950d427af3f8873e635589abc548f0d8a5c6/src/main/groovy/com/thinkimi/gradle/MybatisGeneratorExtension.groovy#L15

Can we make the mybatisProperties as MapProperty<String, String) so that it gets loaded when developer needs to call this task?

**Comment by rajpra8** [comment]
I have created pr https://github.com/kimichen13/mybatis-generator-plugin/pull/19 to address this. Please let me know if this can be merged. Unit test and integration test passed. Please let me know if there is other manual testing I should do.

**Comment by kimichen13** [comment]
Thank you for your feedback, but this plugin should be used in the development phase to generate the related classes based on the table structure. Although lazy property can be used, it just feels very wired.

**Comment by rajpra8** [comment]
@kimichen13 I am using in development phase only but I have kept in main build.gradle. Since some gradle tasks gets used in CI process, its getting loaded because this not being lazy property. Do you see any harm in merging this pr?

**Comment by rajpra8** [comment]
@kimichen13 gentle reminder to reconsider. Please decline the pr if you don't want to merge this pr. I will try to fork and make this change in my forked branch if this change does not belong this repo.

**Comment by kimichen13** [comment]
Thanks to reach out to me again. I will give you response later after few
days, since I’m in Chinese new year holiday now.
