### ISSUE TITLE
Hope to give an example demo

### ISSUE THREAD

**Issue by inke3c** [kimichen13/mybatis-generator-plugin#4]
Direct gradle some dependencies, the old driver may not have pressure, but the novice look more vague.

**Comment by inke88** [comment]
Hello, I have successfully generated Mapper and xml file, but I want the table in the field of comments, how to achieve this?

**Comment by kimichen13** [comment]
I don't know what you want to achieve. `table in the field of comments`?

**Comment by inke3c** [comment]
@kimichen13 
Because I have added a comment in the database table field, I want to generate a comment on the bean field, but now the bean field has no comment

**Comment by kimichen13** [comment]
About the comments, it's the function of mybatis generator. This plugin is only an extra way to generate from database, because the official does not provide the gradle plugin.
