### ISSUE TITLE
无法生成中文注释

### ISSUE THREAD

**Issue by inke3c** [kimichen13/mybatis-generator-plugin#8]
generatorConfig.xml

> 
        <commentGenerator>
            
            <property name="suppressDate" value="true"/>
            
            <property name="suppressAllComments" value="false"/>
            
            <property name="addRemarkComments" value="true" />
            
            <property name="author" value="inke" />
        </commentGenerator>

自动生成后效果如下：

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_info.username
     *
     * @mbg.generated
     */
    private String username;

**Comment by kimichen13** [comment]
可以生成中文注释，之前我用的时候，是自己手动改了mybatis的jar包从取字段comment来做注释，默认支持的配置比较难用。
