### ISSUE TITLE
not work with mysql 8.0 

### ISSUE THREAD

**Issue by C0dErBJ** [kimichen13/mybatis-generator-plugin#9]
not work with mysql 8.0 

`* What went wrong:
Execution failed for task ':main:api:mbGenerator'.
> Unknown system variable 'query_cache_size'
`

**Comment by grath10** [comment]
meet the same problem, how to work with mysql8? Thx!

**Comment by kimichen13** [comment]
`query_cache_size` seems not the parameter for generate. Maybe it should be in the file `generatorConfig.xml'` or on your system.
